# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xacatlahtolli', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Shack',
        ),
    ]
