# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xacatlahtolli', '0002_auto_20170528_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='y',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=175)),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('shack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xacatlahtolli.Shack')),
            ],
        ),
    ]
