# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xacatlahtolli', '0003_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Shack',
            new_name='Language',
        ),
        migrations.RemoveField(
            model_name='y',
            name='shack',
        ),
        migrations.DeleteModel(
            name='y',
        ),
        migrations.AddField(
            model_name='langinfo',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xacatlahtolli.Language'),
        ),
    ]
