# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xacatlahtolli', '0004_auto_20170529_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='langinfo',
            options={'ordering': ['order']},
        ),
    ]
