# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xacatlahtolli', '0005_auto_20170529_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='langinfo',
            name='language',
        ),
        migrations.AddField(
            model_name='language',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
