# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xacatlahtolli', '0006_auto_20170529_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Langinfo',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
