# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xacatlahtolli', '0008_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
