# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papahana', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workbench',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='workbench',
            name='file0',
        ),
        migrations.RemoveField(
            model_name='workbench',
            name='pattern',
        ),
        migrations.AddField(
            model_name='workbench',
            name='data',
            field=models.FileField(default='d', upload_to=''),
        ),
        migrations.AlterField(
            model_name='workbench',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
