# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('papahana', '0002_auto_20180120_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workbench',
            name='data',
        ),
        migrations.RemoveField(
            model_name='workbench',
            name='title',
        ),
        migrations.AddField(
            model_name='workbench',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workbench',
            name='document',
            field=models.FileField(default='d', upload_to='media/'),
        ),
    ]
