# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papahana', '0004_workbench_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workbench',
            name='description',
        ),
    ]
